version: "3.9"

networks:
    laravel:
        name: laravel

services:

    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        depends_on:
            - php
            - mysql
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./library-api:/var/www/html
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./library-api:/var/www/html
        networks:
            - laravel

    mysql:
        image: mysql:8.0.27
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: library_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel
