version: "3.9"

networks:
    library_api:
        name: library_api

services:

    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        depends_on:
            - api
            - db
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./library-api:/var/www/html
        networks:
            - library_api

    db:
        image: mysql:8.0.27
        container_name: db
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: library_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - library_api

    api:
        build:
            context: .
            dockerfile: php.dockerfile
        depends_on:
            - db
        container_name: api
        volumes:
            - ./library-api:/var/www/html
            - ./library-api/.env.example:/var/www/html/.env
        restart: unless-stopped
        command: [sh, -c, "sleep 60 && php artisan migrate && php artisan db:seed"]
        networks:
            - library_api
