version: "3.9"

networks:
    library_api:
        name: library_api

services:

    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        depends_on:
            - api
            - db
        container_name: nginx
        restart: on-failure
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./library-api:/var/www/html
            - ./library-api/storage:/var/www/html/storage
            - ./library-api/books:/var/www/html/books
        networks:
            - library_api

    db:
        image: mysql:8.0.27
        container_name: db
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        restart: on-failure
        environment:
            MYSQL_DATABASE: library_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - library_api

    api:
        build:
            context: .
            dockerfile: php.dockerfile
        depends_on:
            - db
        container_name: api
        volumes:
            - ./library-api:/var/www/html
            - ./library-api/.env.example:/var/www/html/.env
            - ./library-api/storage:/var/www/html/storage
            - ./library-api/books:/var/www/html/books
        networks:
            - library_api

    artisan:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: artisan
        depends_on:
            - api
            - db
        volumes:
            - ./library-api:/var/www/html
        working_dir: /var/www/html
        restart: on-failure
        command: [sh, -c, "php artisan migrate && php artisan db:seed && rm -rf ./public/storage ./public/books && chmod -R 775 ./storage && cd public && ln -s ../storage/app/books books && ln -s ../storage/app/public storage"]
        networks:
            - library_api
        